# Generated by Django 4.0.5 on 2022-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default', upload_to='images/products'),
            preserve_default=False,
        ),
    ]
